modified:   lab3/5 	modified:   lab3/i 	modified:   lab3/v

diff --git a/lab3/i b/lab3/i
--- a/lab3/i
+++ b/lab3/i
@@ -1,4 +1,7 @@
 #!/bin/bash
 name=$(date '+%d.%m.%y_%H:%M:%S')
-mkdir ~/test && echo "catalog test was successfully" >> ~/report.tmp && touch ~/test/$name.tmp
-ping -c 1 www.net_nikogo.ru || echo "ERROR" >> ~/report.tmp
+mkdir ~/test && {
+echo "catalog test was successfully" >> ~/report.tmp
+touch ~/test/$name.tmp
+}
+ping -c 1 www.net_nikogo.ru || echo "$name ERROR" >> ~/report.tmp
diff --git a/lab3/v b/lab3/v
--- a/lab3/v
+++ b/lab3/v
@@ -3,15 +3,20 @@
 while true
 do
 	read line
+	echo "$line" >> 5.in
+
 	if [[ $line == "QUIT" ]]
-		then
+		then	
+			echo "the planned quit"
 			rm 5.in
-			exit
+			exit 0
 	fi
-	if [[ $line == "*" ]]
-		then 
-			echo "*" >> 5.in
-		else
-			echo $line >> 5.in
+	
+	if [[ $line != "+" && $line != "*" && ! $line =~ [0-9]+ ]]
+		then
+			echo "ERROR"
+			rm 5.in
+			exit 1
 	fi	
 done
+
